// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nodinite")
	ScopeName = "github.com/syron/nodiniteexporter/nodiniteexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
